version: '3'
services:
    redis:
      image: bitnami/redis:latest
      container_name: redis
      expose:
        - "6379"
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      networks:
        - net-host

    apex:
      build:
          context: ./apex
          dockerfile: Dockerfile
      command: gunicorn --bind 0.0.0.0:5000 wsgi:app
      container_name: apex
      ports:
        - 5000:5000
      networks:
        - net-host
    
    celery:
      build:
          context: ./apex
          dockerfile: Dockerfile
      command: celery -A wsgi:celery worker -l INFO
      depends_on:
        - redis
      networks:
        - net-host

networks:
  net-host:
    external: true
